services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    container_name: portfolio-analyzer-backend
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped
    networks:
      - portfolio-network
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: portfolio-analyzer-frontend
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000  # Using service name for internal communication
      - NODE_ENV=production
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      - /app/node_modules
      - /app/build
    restart: unless-stopped
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
